name: Build and Release IPK

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'luasrc/**'
      - 'root/**'

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Install dependencies
      run: |
          sudo -E apt -yqq update
          sudo -E apt -yqq full-upgrade
          sudo -E apt -yqq autoremove --purge
          sudo -E apt -yqq autoclean
          sudo -E apt -yqq clean
          sudo -E apt -yqq install build-essential libncurses5-dev gawk git gettext libssl-dev xsltproc zip
          sudo -E systemctl daemon-reload
          sudo -E timedatectl set-timezone "Asia/Shanghai"

          echo "WRT_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")" >> $GITHUB_ENV

    - name: Download SDK
      run: |
        wget https://downloads.immortalwrt.org/snapshots/targets/mediatek/filogic/immortalwrt-sdk-mediatek-filogic_gcc-13.3.0_musl.Linux-x86_64.tar.zst
        tar -J -x -f immortalwrt-sdk-*.tar.xz

    - name: Build IPK
      run: |
        cd ./immortalwrt-sdk-*/
        ./scripts/feeds update -a
        ./scripts/feeds install -a

        cd ./package/
        git clone --depth=1 --single-branch https://github.com/VIKINGYFY/luci-app-advancedplus.git

        cd ..
        make defconfig
        make package/luci-app-advancedplus/compile V=s

        mkdir ./upload/
        find ./bin/ -type f "*.ipk" -exec mv -f {} ./upload/ \;

    - name: Release IPK
      uses: softprops/action-gh-release@master
      with:
        tag_name: ${{env.WRT_DATE}}
        files: ./immortalwrt-sdk-*/upload/*.*
        body: |
          Automated release
